### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by groe** [evo42/willzahlen.at#1]
I would be interested in having a look at it but I can't find the code :(

**Comment by evo42** [comment]
The code is currently still at a private repos @ bitbucket -- need to clean up a bit (unused test code, hard coded passwords ... + fix some spaghetti code [like settimeout() instead of promises])

It will be available in the next one or two days.

I'm also waiting for the free SSL cert I applied to: https://godaddy.com/ssl/ssl-open-source.aspx

**Comment by groe** [comment]
Great, thanks! :)

**Comment by evo42** [comment]
code for v1.0-rc1 pushed with 1270b6e88db0c3b3b892f09ce5e6ead9d932b696 -- (new feature: added drag&drop upload)
